baseURL = 'http://glowing-telegram.com/'
languageCode = 'en-AU'
title = 'Glowing Telegram'
theme = "terminal"

[params]
contentTypeName = "definition"
fullWidthTheme = false
centerTheme = true
logo.logoText = "Glowing Telegram"

[Menus]
  main = [
  ]